# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle
 
name: Delete Package
env:
  ORG: "imprivata-pam"
  REPO: "cas"
on: workflow_dispatch
jobs:
  build:
 
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
 
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
 
    - name: Delete packages
      run: |
            curl -L   -H "Accept: application/vnd.github+json"   -H "Authorization: Bearer ${{github.token}}" -H "X-GitHub-Api-Version: 2022-11-28" "https://api.github.com/orgs/${{env.ORG}}/packages?package_type=maven&repo_name=${{env.REPO}}&per_page=100" | jq '.[].name' | sed -e s/\"//g |xargs -I {} curl -L -X DELETE -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{github.token}}" -H "X-GitHub-Api-Version: 2022-11-28"  https://api.github.com/orgs/${{env.ORG}}/packages/maven/{}
      shell: bash
